version: '3.7'

services:
  tech-task-dev-backend:
    image: joepalmeras66/tech-task-dev-backend:${TECH_TASK_VERSION:-latest}
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_CONTAINER_NAME:-postgres_container}:5432/db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    networks:
      - db_net
    depends_on:
      - postgres

  postgres:
    container_name: ${DB_CONTAINER_NAME:-postgres_container}
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db_net
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - db_net
    depends_on:
      - postgres
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    environment:
      URLS_PRIMARY_NAME: "Petstore"
      URLS: "[{ url: 'https://gist.githubusercontent.com/JoePalmeras66/5841f6371c95614e7ea0b285e9b6ab30/raw/cb4dcbf2a0a85c461e6fa1266dc10750379aeb0b/openapi-randomusers.yaml', name: 'RandomUsers'},
              { url: 'https://petstore.swagger.io/v2/swagger.json', name: 'Petstore'},
            ]"

networks:
  db_net:
    driver: bridge

volumes:
    postgres:
    pgadmin: