version: '3.7'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./swagger/openapi-randomusers.yaml:/openapi-randomusers.yaml
    environment:
      SWAGGER_JSON: /openapi-randomusers.yaml
      # API_URL: ""
    networks:
      - swagger_net
    depends_on:
      - tech-task-dev-backend

  swagger-api:
    image: danielgtaylor/apisprout
    container_name: "swagger-api"
    ports:
      - "8083:8000"
    volumes:
      - ./swagger/openapi-randomusers.yaml:/openapi-randomusers.yaml
    command: /openapi-randomusers.yaml
    networks:
      swagger_net:
        aliases:
          - local.swagger.apisprout
    depends_on:
      - tech-task-dev-backend

  swagger-nginx:
    image: nginx:mainline-alpine
    container_name: "swagger-nginx"
    ports:
      - "8084:8084"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      swagger_net:
        aliases:
          - local.swagger.api
    depends_on:
      - tech-task-dev-backend

networks:
  swagger_net:
    driver: bridge

volumes:
  swagger:
  nginx: