/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.demicon.tech.task.d3.cloud;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
